### ISSUE TITLE
android模版仓库问题

### ISSUE THREAD

**Issue by zht110227** [weexteam/app-framework-android#4]
classpath 'com.taobao.android:weexplugin-gradle-plugin:1.1.3-SNAPSHOT'
这个包下载不了，模版里面给出的仓库访问不了，找不到这个包？

**Comment by q757571446** [comment]
maven { url "http://mvnrepo.alibaba-inc.com/mvn/repository" }
他们把自己mvn私服丢上来了，外网访问不到。然后这个插件weexplugin-gradle-plugin也不发布。所以你下不了

**Comment by q757571446** [comment]
老铁，你如果懂安卓的话可以把weexplugin这个模块重新Include到工程里面去。他们想自己做个gradle插件加载weex plugin add xxx安装的那些依赖。然而gradle插件没发布，然而你依然只能用以前weexplugin模块加载安装的插件

**Comment by erha19** [comment]
@q757571446 You are right, it's a mistake by me, and this plugin will be released soon.

**Comment by misakuo** [comment]
We just released the plugin development kit including [weexplugin-annotation](https://bintray.com/alibabaweex/maven/weexplugin-annotation), [weexplugin-processor](https://bintray.com/alibabaweex/maven/weexplugin-processor), [weexplugin-loader](https://bintray.com/alibabaweex/maven/weexplugin-loader) and [weexplugin-gradle-plugin](https://bintray.com/alibabaweex/maven/weexplugin-gradle-plugin) to [jcenter](https://bintray.com/alibabaweex/maven).

**Comment by zht110227** [comment]
现在已经把包放到jcenter中了吗？

**Comment by passioncsu** [comment]
仓库无法访问的这个问题问了一圈   时隔半年这个问题竟然还在..这还怎么玩啊,难道weex已经凉了嘛...我才开始学啊
==========踩坑归来的我更新一下=====
# 首先是gradle 找不到的原因google官方下没有东西,据说搬到这里了bintray.com修改如下
```
buildscript {
    repositories {
        mavenLocal()
        jcenter()
        mavenCentral()
        maven {
            url 'http://dl.bintray.com/alibabaweex/maven/'
            name 'aliyun'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.2'
        classpath 'com.taobao.android:weexplugin-gradle-plugin:1.3'
    }
}
```
# 然后我还被提示 Cause: jcenter.bintray.com:443 failed to respond
```
可能是代理的问题,去配置文件下删除代理信息
vim ~/.gradle/gradle.properties
删掉下面那些代理信息.
```
又是坑了我两个小时.....

**Comment by erha19** [comment]
This issue has been fixed. Close
