### ISSUE TITLE
Could not find com.alibaba:fastjson:1.1.27-android

### ISSUE THREAD

**Issue by mario-huang** [weexteam/app-framework-android#8]
The annotationProcessor 'com.taobao.android:weexplugin-processor:1.3' dependencies on com.alibaba:fastjson:1.1.27-android, but "Could not find com.alibaba:fastjson:1.1.27-android."

**Comment by huangminlinux** [comment]
## Environment
```
➜ weex --version
 - weexpack : v1.2.3
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1
```
## Description
```
➜ weex plugin create my-weex-plugin
➜ cd my-weex-plugin
# open ./playground/android  with android studio3.0 
```
when building gradle and get Error:Failed to resolve: com.alibaba:fastjson:1.1.27-android

**Comment by baivoom** [comment]
In fact  after searching the maven repository,  the 'com.taobao.android:weexplugin-processor:1.3' depends on the 'com.alibaba:fastjson:1.1.27-android' which does not exist. I have to remove this process or from build.gradle and then the project got compiled successfully. But I not sure if the weex will work as expected.  Just wonder,  is the weex project totally dead or just dead for opensource project?

**Comment by mario-huang** [comment]
@baivoom nice question.

**Comment by soaringEveryday** [comment]
issue can not be reproduced, could you please run command 'weex platform list', and check the 'Installed platforms' items, the version should be android 6.3.17. If that, you can find that already import fastjson v1.1.46

**Comment by soaringEveryday** [comment]
@myeveryheart

**Comment by huangminlinux** [comment]
```
➜  awesome-app weex platform list
Installed platforms:


Available platforms:
- android ^6.3.8
  - ios ^4.1.6
```

**Comment by huangminlinux** [comment]
cann't run `weex platform list` in weex plugin project, I mean the playground ( create by weex plugin create my-weex-plugin )
But I get this error in weex plugin project.

**Comment by erha19** [comment]
Maybe @tralves can answer @huangminlinux 's questions, I have tested the template on my platform, it works ok for me.

**Comment by olivercm** [comment]
Could not find com.alibaba:fastjson:1.1.27-android.
Searched in the following locations:
    file:/Users/xxx/Library/Android/sdk/extras/m2repository/com/alibaba/fastjson/1.1.27-android/fastjson-1.1.27-android.pom
    file:/Users/xxx/Library/Android/sdk/extras/m2repository/com/alibaba/fastjson/1.1.27-android/fastjson-1.1.27-android.jar
    file:/Users/xxx/Library/Android/sdk/extras/google/m2repository/com/alibaba/fastjson/1.1.27-android/fastjson-1.1.27-android.pom
    file:/Users/xxx/Library/Android/sdk/extras/google/m2repository/com/alibaba/fastjson/1.1.27-android/fastjson-1.1.27-android.jar
    file:/Users/xxx/Library/Android/sdk/extras/android/m2repository/com/alibaba/fastjson/1.1.27-android/fastjson-1.1.27-android.pom
    file:/Users/xxx/Library/Android/sdk/extras/android/m2repository/com/alibaba/fastjson/1.1.27-android/fastjson-1.1.27-android.jar
    file:/Users/xxx/.m2/repository/com/alibaba/fastjson/1.1.27-android/fastjson-1.1.27-android.pom
    file:/Users/xxx/.m2/repository/com/alibaba/fastjson/1.1.27-android/fastjson-1.1.27-android.jar
    https://jcenter.bintray.com/com/alibaba/fastjson/1.1.27-android/fastjson-1.1.27-android.pom
    https://jcenter.bintray.com/com/alibaba/fastjson/1.1.27-android/fastjson-1.1.27-android.jar
    https://repo.maven.apache.org/maven2/com/alibaba/fastjson/1.1.27-android/fastjson-1.1.27-android.pom
    https://repo.maven.apache.org/maven2/com/alibaba/fastjson/1.1.27-android/fastjson-1.1.27-android.jar
    https://maven.google.com/com/alibaba/fastjson/1.1.27-android/fastjson-1.1.27-android.pom
    https://maven.google.com/com/alibaba/fastjson/1.1.27-android/fastjson-1.1.27-android.jar

Required by:
    project :app > com.taobao.android:weexplugin-processor:1.3  

download pom、jar file,  and put them in your local file can fix it  
https://yun.baidu.com/share/link?shareid=4294337343&uk=1561289668&fid=393924576692924  
https://repo.maven.apache.org/maven2/com/alibaba/fastjson/1.1.27/fastjson-1.1.27.pom

**Comment by thirtyyuan** [comment]
1. Can I remove this dependency from my `build.gradle`? 
2. I find `com.alibaba:fastjson:1.2.41` is in our private maven repository, so when I replace `com.alibaba:fastjson:1.2.41.android` by `com.alibaba:fastjson:1.2.41`, I didn't get any error, but I'm not sure does it correctly? Anyone could tell the different between `com.alibaba:fastjson:1.2.41.android` with `com.alibaba:fastjson:1.2.41`?
